version: '3.9'

services:

  postgres-trigger-strategy:
    build: ./postgresql
    restart: always
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_PASSWORD=pgadmin
