version: '3.9'

services:

  postgres-trigger-strategy:
    build: ./postgresql
    restart: always
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=pgadmin
    volumes:
      - 'postgres-trigger-strategy-data:/var/lib/postgresql/data'

  zookeeper-trigger-strategy:
    image: zookeeper:latest
    restart: always
    ports:
      - "2181:2181"
      - "2888:2888"
      - "3888:3888"

  kafka-trigger-strategy:
    image: bitnami/kafka:3.4
    restart: always
    links:
      - zookeeper-trigger-strategy
    environment:
      - KAFKA_CFG_ZOOKEEPER_CONNECT=zookeeper-trigger-strategy:2181
    ports:
      - "9092:9092"

  kafka-ui-trigger-strategy:
    image: provectuslabs/kafka-ui:latest
    restart: always
    ports:
      - "8080:8080"
    links:
      - kafka-trigger-strategy
    environment:
      DYNAMIC_CONFIG_ENABLED: 'true'
    volumes:
      - kafka-ui-trigger-strategy-data:/etc/kafkaui

  elasticsearch-trigger-strategy:
    container_name: elasticsearch-trigger-strategy
    image: docker.elastic.co/elasticsearch/elasticsearch:7.10.2
    restart: always
    ports:
      - "9200:9200"
    environment:
      - http.host=0.0.0.0
      - transport.host=127.0.0.1
      - xpack.security.enabled=false
      - "discovery.type=single-node"
      - "ES_JAVA_OPTS=-Xms512m -Xmx512m"

  kibana-trigger-strategy:
    container_name: kibana-trigger-strategy
    image: docker.elastic.co/kibana/kibana:7.10.2
    ports:
      - '5601:5601'
    depends_on:
      - elasticsearch-trigger-strategy
    environment:
      SERVER_NAME: kibana.example.org
      ELASTICSEARCH_HOSTS: '["http://elasticsearch-trigger-strategy:9200"]'

  postgres-worker-trigger-strategy:
    build: ./worker/postgres-worker
    restart: always
    depends_on:
      - kafka-trigger-strategy
      - postgres-trigger-strategy
    links:
      - kafka-trigger-strategy
      - postgres-trigger-strategy
    environment:
      - database=employee_db
      - user=postgres
      - password=pgadmin
      - port=5432
      - host=postgres-trigger-strategy
      - KAFKA_BROKER=kafka-trigger-strategy:9092

  elastic-worker-trigger-strategy:
    build: ./worker/elastic-worker
    restart: always
    depends_on:
      - kafka-trigger-strategy
    links:
      - kafka-trigger-strategy
    environment:
      - KAFKA_BROKER=kafka-trigger-strategy:9092
      - ELASTICSEARCH_URL=http://elasticsearch-trigger-strategy:9200

volumes:
   postgres-trigger-strategy-data:
       name: postgres-trigger-strategy-data
       driver: local
   kafka-ui-trigger-strategy-data:
        name: kafka-ui-trigger-strategy-data
        driver: local